/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package board_model1._0_mybatis_gradle;



public class LibraryTest {
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
       
    }
}
