/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package guest_model1._0_mybatis_gradle;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
      
    }
}
