/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package web_project_shop_template_gradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
