/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package guest_model1._0_mybatis_gradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
